Seed:
  - seed
  - seeds
  - sow
  - sowing
  - germinate
  - germination
  - after-ripening
  - dry storage
  - pre-treatment
  - pretreatment
  - soaking
  - boiling water
  - hot water
  - stratification
  - cold storage
  - cold treatment
  - smoke
  - smoke water
  - smoke extract
  - leach
  - leaching
  - running water
Cutting:
  - cutting
  - cuttings
  - stem cutting
  - root cutting
  - leaf cutting
  - strike readily
  - rooting
  - wounding
  - rooting hormone
  - indole butyric acid
  - iba
  - naphthalene acetic acid
  - naa
Division:
  - divide
  - divided
  - division
  - rhizome division
  - rhizome segment
  - rhizome segments
  - stolon division
  - layering
